apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rotisserie.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  token: {{ .Values.secrets.token }}
  clientID: {{ .Values.secrets.clientID }}
